import React, { useState } from 'react';
import { FaTasks } from 'react-icons/fa';
import { NavLink } from 'react-router-dom';
import { AiOutlinePlus } from 'react-icons/ai';
import { FaRobot } from 'react-icons/fa';
import { MdAutoAwesome } from 'react-icons/md';
import {
     Box,
     Button,
     Flex,
     HStack,
     Heading,
     Spacer,
     Text,
     Modal,
     ModalOverlay,
     ModalContent,
     ModalHeader,
     ModalBody,
     useDisclosure,
     Select,
     Textarea,
     Input,
     Spinner,
} from '@chakra-ui/react';
import { motion } from 'framer-motion';
import { useDispatch, useSelector } from 'react-redux';
import useToastMsg from '../customHooks/useToastMsg';
import { postTask, generateDescriptionForTask } from '../redux/tasks/tasks.actions';
import TaskBot from './TaskBot';

// Motion wrapper for animated button
const MotionButton = motion(Button);

function Navbar() {
     const { data } = useSelector(store => store.tasksManager);
     const { isOpen, onOpen, onClose } = useDisclosure()
     const [subtasks, setSubtasks] = useState([""]);
     const [isTaskBotOpen, setIsTaskBotOpen] = useState(false);
     const dispatch = useDispatch();
     const toastMsg = useToastMsg();
     const [isGenerating, setIsGenerating] = useState(false);


     const handleSubmit = (e) => {
          e.preventDefault();
          const { title, desc, status } = e.target;
          const task = {
               title: title.value,
               description: desc.value,
               status: status.value,
               subtask: subtasks.filter(e => e)
          }

          dispatch(postTask(data._id, task, toastMsg))

          e.target.reset()
          setSubtasks([""])
          onClose()
     }

     const handleAddSubTaskInput = () => {
          setSubtasks([...subtasks, ''])
     }

     const handleGenerateDescCreate = async () => {
          const titleEl = document.getElementById('title');
          const descEl = document.getElementById('desc');
          if (!titleEl || !titleEl.value) {
               toastMsg({ title: 'Task title is required', desc: 'Please enter a task name first', status: 'warning' })
               return;
          }
          setIsGenerating(true);
          try {
               const result = await dispatch(generateDescriptionForTask(titleEl.value));
               if (result && result.ok && result.description) {
                    if (descEl) descEl.value = result.description;
                    toastMsg({ title: result.message || 'Task description generated by AI', status: 'success' });
               } else {
                    console.error(result?.message);
                    toastMsg({ title: 'Failed to generate description', status: 'warning' });
               }
          } catch (err) {
               console.log('generate desc error:', err);
               //    toastMsg({ title: 'Error generating description', status: 'error' });
          } finally {
               setIsGenerating(false);
          }
     }

     const handleChange = (e, i) => {
          let valueChangedSubTasks = [...subtasks];
          valueChangedSubTasks[i] = e.target.value;
          setSubtasks(valueChangedSubTasks);
     }

     const handleDeleteSubTask = (ind) => {
          let updatedSubTasks = [...subtasks];
          updatedSubTasks.splice(ind, 1);
          setSubtasks(updatedSubTasks)
     }

     const hasBoard = Boolean(data && data._id);

     const handleOpenCreate = () => {
          if (!hasBoard) {
               toastMsg({ title: 'Select a board first', desc: 'Please select a board before creating tasks', status: 'warning' });
               return;
          }
          onOpen();
     }

     const handleOpenTaskBot = () => {
          if (!hasBoard) {
               toastMsg({ title: 'Select a board first', desc: 'Please select a board to use AI create', status: 'warning' });
               return;
          }
          setIsTaskBotOpen(true);
     }

     return (
          <>
               <Flex minWidth='max-content' alignItems='center' gap='2' p="10px 15px" bgColor="#fff" position='sticky' top='0' left='0' zIndex='5'>
                    <Box p='2'>
                         <NavLink to="/">
                              <HStack>
                                   <FaTasks fontSize="20px" />
                                   <Heading display={{ base: 'none', sm: 'inline-block' }} size='md'>Kanban Board</Heading>
                              </HStack>
                         </NavLink>
                    </Box>
                    <Spacer />
                    <HStack spacing='2'>
                         <Button
                              onClick={handleOpenCreate}
                              title='Add New Task'
                         >
                              <HStack>
                                   <AiOutlinePlus />
                                   <Text>Add New Task</Text>
                              </HStack>
                         </Button>
                         <Button
                              onClick={handleOpenTaskBot}
                              variant='outline'
                              colorScheme='purple'
                              title='Create Task using AI'
                         >
                              <HStack>
                                   <FaRobot />
                                   <Text>AI Create</Text>
                              </HStack>
                         </Button>
                    </HStack>
               </Flex>
               <TaskBot isOpen={isTaskBotOpen} onClose={() => setIsTaskBotOpen(false)} />


               {/* Create Task Modal */}
               <Modal isOpen={isOpen} onClose={onClose}>
                    <ModalOverlay />
                    <ModalContent>
                         <ModalHeader>Add New Task</ModalHeader>
                         <ModalBody>
                              <form id="create-task-form" onSubmit={handleSubmit}>
                                   <div className='input-div'>
                                        <label>Task Name</label>
                                        <Input id='title' type="text" required />
                                   </div>
                                   <div className='input-div'>
                                        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                                             <label>Description</label>
                                             <MotionButton
                                                  isDisabled={isGenerating}
                                                  onClick={handleGenerateDescCreate}
                                                  size='xs'
                                                  bg='linear-gradient(135deg, #667eea 0%, #764ba2 100%)'
                                                  color='white'
                                                  _hover={!isGenerating ? {
                                                       bg: 'linear-gradient(135deg, #764ba2 0%, #667eea 100%)',
                                                       boxShadow: '0 0 20px rgba(102, 126, 234, 0.6)',
                                                  } : {}}
                                                  fontWeight='600'
                                                  fontSize='xs'
                                                  borderRadius='md'
                                                  padding='4px 8px'
                                                  title='Generate description with AI'
                                             >
                                                  {isGenerating ? (
                                                       <>
                                                            <Spinner size='xs' color='white' />
                                                            <Text ml='2'>Generating...</Text>
                                                       </>
                                                  ) : (
                                                       <>
                                                            <MdAutoAwesome size={18} />
                                                            <Text ml='1'>AI Generate</Text>
                                                       </>
                                                  )}
                                             </MotionButton>
                                        </div>
                                        <Textarea id='desc' cols="30" rows="3" required></Textarea>
                                   </div>
                                   <div className='input-div'>
                                        <label>Subtasks</label>
                                        {
                                             subtasks.map((el, i) => <div key={i} className='subtask-input'>
                                                  <Input type='text' value={el} onChange={(e) => handleChange(e, i)} />
                                                  <Text role='button' onClick={() => handleDeleteSubTask(i)}>❌</Text>
                                             </div>)
                                        }
                                        <Button onClick={handleAddSubTaskInput}>+ Add New Subtask</Button>
                                   </div>
                                   <div className='input-div'>
                                        <label>Current Status</label>
                                        <Select id='status' required>
                                             <option value="Todo">➕ Todo</option>
                                             <option value="Doing">⏳ Doing</option>
                                             <option value="Done">✔ Done</option>
                                        </Select>
                                   </div>
                                   <Button type='submit' isLoading={false}>Create Task</Button>
                              </form>
                         </ModalBody>
                    </ModalContent>
               </Modal >
          </>
     )
}

export default Navbar